name: Build_AAB

on:
  workflow_dispatch:

jobs:
  build-android:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Fix Git extraheader permission issue
        run: git config --global --unset-all "http.https://github.com/.extraheader" || true

      - name: Build with Buildozer
        uses: ArtemSBulgakov/buildozer-action@v1
        id: buildozer
        with:
          workdir: .
          buildozer_version: stable
          command: buildozer android release

      - name: Compute tag
        id: vars
        run: echo "tag=v0.0.${{ github.run_number }}" >> $GITHUB_OUTPUT

      - name: Upload file to GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.vars.outputs.tag }}
          files: ${{ steps.buildozer.outputs.filename }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
